#!/bin/sh

### BEGIN INIT INFO
# Provides: bluepill_glue
# Required-Start:    $local_fs $remote_fs $network $syslog $time
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: bluepill daemon, providing process monitoring
# Description: bluepill is a monitoring tool. More info at http://github.com/arya/bluepill.
### END INIT INFO
# set -e

. /lib/lsb/init-functions

# here comes default config
USER=nginx
APP_NAME=bluepill_glue
APP_ROOT=/var/www/deployments/gluedb/current
PILL=$APP_ROOT/pills/gluedb.pill.rb
CMD="sudo -i -u $USER -- /bin/bash -c 'cd $APP_ROOT && bluepill --no-privileged -c $APP_ROOT/pids/ -l $APP_ROOT/log/bluepill.log"

case "$1" in
    start)
        echo -n "Starting bluepill for user $USER"
        eval "$CMD load $PILL'"
        ;;
    stop)
        echo "Shutting down monitored processes"
        eval "$CMD stop'"

        echo "Shutting down bluepill daemon"
        eval "$CMD quit'"
        ;;
    restart)
        ## Stop the service and regardless of whether it was
        ## running or not, start it again.
        $0 stop
        $0 start
        ;;
    status)
        eval "$CMD status'"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
